[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
