[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]
aptPkgs = ["curl"]

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && node src/index.js"

[variables]
NODE_ENV = "production"
PORT = "3001"
