[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install --production"

[deploy]
startCommand = "cd backend && node src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"
